export const SET_INITIAL_CHARGE = "SET_INITIAL_CHARGE";
export const ADD_QUESTIONS = "ADD_QUESTIONS";
export const CHANGE_SORT = "CHANGE_SORT";
export const CHANGE_PAGE = "CHANGE_PAGE";
export const CHANGE_SEARCH = "CHANGE_SEARCH";